# OVERRIDE #

languageCode = "en-us"
title = "Codex"
baseURL = "https://example.org/"
copyright = "Â© {year}"

[params]

  name = "Codex"
  description = "A minimal blog theme for hugo."
  twitter = "hugo-theme-codex"
  github = "jakewies/hugo-theme-codex"

# OVERRIDE #

# DONT OVERRIDE #

preserveTaxonomyNames = true

[taxonomies]
  tag = "tags"

# DONT OVERRIDE #
